CC=gcc
CFLAGS=-I.

all: matrix_multiply

matrix_multiply: ThreadedMatrixMultiply.o
	$(CC) -o matrix_multiply ThreadedMatrixMultiply.o -lpthread

ThreadedMatrixMultiply.o: ThreadedMatrixMultiply.c
	$(CC) -c ThreadedMatrixMultiply.c $(CFLAGS)

clean:
	rm -f *.o matrix_multiply
